"""remove output format and json schema

Revision ID: 4a84e2de9864
Revises: 0041
Create Date: 2026-03-06 18:11:36.203843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a84e2de9864'
down_revision = '0041'
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if inspector.has_table("evolink_settings"):
        evolink_cols = {c["name"] for c in inspector.get_columns("evolink_settings")}
        if "understand_json_schema" in evolink_cols:
            op.drop_column('evolink_settings', 'understand_json_schema')
        if "understand_output_format" in evolink_cols:
            op.drop_column('evolink_settings', 'understand_output_format')
    pipeline_cols = {c["name"] for c in inspector.get_columns("pipeline_settings")}
    if "understand_json_schema" in pipeline_cols:
        op.drop_column('pipeline_settings', 'understand_json_schema')
    if "understand_output_format" in pipeline_cols:
        op.drop_column('pipeline_settings', 'understand_output_format')
    op.execute("ALTER TABLE pipeline_settings DROP COLUMN IF EXISTS upscaling_api_url")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline_settings', sa.Column('understand_output_format', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('pipeline_settings', sa.Column('upscaling_api_url', sa.VARCHAR(length=500), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.add_column('pipeline_settings', sa.Column('understand_json_schema', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('evolink_settings', sa.Column('understand_output_format', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('evolink_settings', sa.Column('understand_json_schema', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
