"""add shots to daily_generations

Revision ID: 52dcecd3eb21
Revises: ddaffbdbfb54
Create Date: 2026-03-05 11:26:53.157677

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '52dcecd3eb21'
down_revision = 'ddaffbdbfb54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    bind.execute(sa.text("DROP INDEX IF EXISTS ix_subtask_generated_videos_subtask_id"))
    bind.execute(sa.text("DROP TABLE IF EXISTS subtask_generated_videos"))
    op.add_column('daily_generations', sa.Column('shots', sa.JSON(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_generations', 'shots')
    op.create_table('subtask_generated_videos',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subtask_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('object_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('extra', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subtask_id'], ['subtasks.id'], name='subtask_generated_videos_subtask_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='subtask_generated_videos_pkey')
    )
    op.create_index('ix_subtask_generated_videos_subtask_id', 'subtask_generated_videos', ['subtask_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('comfyui_server_ip', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('comfyui_ports', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('evolink_api_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('evolink_api_base_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name='system_settings_pkey')
    )
    op.create_table('pipeline_settings',
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('understand_model', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('understand_prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('understand_temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('understand_output_format', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('understand_json_schema', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('owner_id', name='pipeline_settings_pkey')
    )
    # ### end Alembic commands ###
