"""add owner_id to daily_generations

Revision ID: ddaffbdbfb54
Revises: 0032
Create Date: 2026-03-05 11:21:23.222401

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ddaffbdbfb54'
down_revision = '0032'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Ensure daily_generations table exists before adding columns
    # (the table was created via create_all on local, but never had a CREATE migration)
    bind = op.get_bind()
    bind.execute(sa.text("""
        CREATE TABLE IF NOT EXISTS daily_generations (
            id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
            target_date DATE NOT NULL,
            sort_order INTEGER NOT NULL DEFAULT 0,
            prompt TEXT NOT NULL,
            image TEXT NOT NULL,
            duration VARCHAR(50) NOT NULL
        )
    """))
    bind.execute(sa.text("CREATE INDEX IF NOT EXISTS ix_daily_generations_target_date ON daily_generations (target_date)"))

    # Drop tables that may or may not exist depending on the DB state
    bind.execute(sa.text("DROP INDEX IF EXISTS ix_subtask_generated_videos_subtask_id"))
    bind.execute(sa.text("DROP TABLE IF EXISTS subtask_generated_videos"))
    op.add_column('daily_generations', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.create_index(op.f('ix_daily_generations_owner_id'), 'daily_generations', ['owner_id'], unique=False)
    op.alter_column('subtasks', 'result',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.create_foreign_key(None, 'subtasks', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.alter_column('task_templates', 'workflow_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('tasks', 'workflow_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'workflow_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('task_templates', 'workflow_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'subtasks', type_='foreignkey')
    op.alter_column('subtasks', 'result',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index(op.f('ix_daily_generations_owner_id'), table_name='daily_generations')
    op.drop_column('daily_generations', 'owner_id')
    op.create_table('subtask_generated_videos',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subtask_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('object_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('extra', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['subtask_id'], ['subtasks.id'], name='subtask_generated_videos_subtask_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='subtask_generated_videos_pkey')
    )
    op.create_index('ix_subtask_generated_videos_subtask_id', 'subtask_generated_videos', ['subtask_id'], unique=False)
    op.create_table('pipeline_settings',
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('understand_model', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('understand_prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('understand_temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('understand_output_format', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('understand_json_schema', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('owner_id', name='pipeline_settings_pkey')
    )
    op.create_table('system_settings',
    sa.Column('key', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('comfyui_server_ip', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('comfyui_ports', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('evolink_api_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('evolink_api_base_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name='system_settings_pkey')
    )
    # ### end Alembic commands ###
